### ISSUE TITLE
BigInteger causes StackOverflow error

### ISSUE THREAD

**Issue by LenarBad** [LenarBad/easylog#33]
```
java.lang.StackOverflowError
	at java.math.MutableBigInteger.divideMagnitude(MutableBigInteger.java:1488)
	at java.math.MutableBigInteger.divideKnuth(MutableBigInteger.java:1227)
	at java.math.MutableBigInteger.divide(MutableBigInteger.java:1153)
	at java.math.MutableBigInteger.divide(MutableBigInteger.java:1147)
	at java.math.BigInteger.smallToString(BigInteger.java:3583)
	at java.math.BigInteger.toString(BigInteger.java:3549)
	at java.math.BigInteger.toString(BigInteger.java:3710)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractMap.toString(AbstractMap.java:536)
	at io.lenar.easy.log.support.Processor.processMap(Processor.java:85)
	at io.lenar.easy.log.support.Processor.processObject(Processor.java:35)
	at io.lenar.easy.log.support.Processor.processMap(Processor.java:89)
	at io.lenar.easy.log.support.Processor.processObject(Processor.java:35)
	at io.lenar.easy.log.support.Processor.processMap(Processor.java:89)
	at io.lenar.easy.log.support.Processor.processObject(Processor.java:35)
	at io.lenar.easy.log.support.Processor.processMap(Processor.java:89)
        ...
```

Most likely including BigInteger into "PRIMITIVE" will fix the issue

**Comment by LenarBad** [comment]
Fixed
released in 1.1.1
